user auth commit
LaunchCodeLiftoffProjects/recipe-app pull request #4
Opened 2020-12-10 01:26 UTC by pgwcfx

pull

2020-12-10 02:04 UTC, ryanawalker requested changes

2020-12-10 02:04 UTC, ryanawalker commented on src/main/java/org/launchcode/recipeapp/controllers/AuthenticationController.java
> +            User newUser = new User(registerFormDTO.getUsername(), registerFormDTO.getPassword());
Would suggest replacing `registerFormDTO.getPassword()` with `password` since you've already stored the variable.

2020-12-10 02:04 UTC, ryanawalker commented on src/main/java/org/launchcode/recipeapp/controllers/AuthenticationController.java
> +            User newUser = new User(registerFormDTO.getUsername(), registerFormDTO.getPassword());
And possibly the username as well, if we're getting it from the DTO twice, let's just store it in a variable.

2020-12-10 02:14 UTC, dsigbeku reviewed
looks good to me apart from the changes Ryan made

2020-12-14 02:42 UTC, zoelzer220 commented
Looks good to me! Worked great.

2020-12-14 19:55 UTC, ryanawalker commented
> 
> 
> Looks good to me! Worked great.
> 
> When would we talk about what other fields we could add? I'm not sure there are any for this project specifically, but thinking Name or email or anything might be helpful for like resetting a password or something like that.

In actual practice, implementing something like password reset would probably be its own story, and we'd add the necessary fields then and deploy a spot for users to back-populate any fields that need it (i.e. a pop-up on the next time they log in telling them to add whatever to their profile).

If you think there's a good argument to add email address now (and I think there could be) then you can absolutely request it as a change.

2020-12-15 02:32 UTC, ryanawalker approved these changes

2020-12-15 02:33 UTC, merged

2020-12-15 02:33 UTC, pgwcfx commented on src/main/java/org/launchcode/recipeapp/controllers/AuthenticationController.java
> +            User newUser = new User(registerFormDTO.getUsername(), registerFormDTO.getPassword());
I made those requested changes